### ISSUE TITLE
Add to Spark module on/off led

### ISSUE THREAD

**Issue by BorisPlintovic** [brett8883/Super-Firmware_Cache#1]
g_cfg_debug_force_flash_led 
Back arms led must be set off on module...in standard is this parameter closed so nfz or altitude

g_config_misc_cfg_forearm_led_ctrl
Front arms led can be on/off any time in assistant

**Comment by brett8883** [comment]
Did you try https://github.com/brett8883/Super-Firmware_Cache/tree/2.0/Spark/Spark%20Variants/Spark_Stealth_SP_variant ? 

Also this repo is under construction.

**Comment by brett8883** [comment]
@BorisPlintovic I don't understand the issue you have brought up. Can you please clarify or I'm gonna close this issue
